In [7]:
import numpy as np
a = np.array([1,3,5])
b = np.array([1,2,3])
print(a*b)

[ 1  6 15]


In [27]:

a=np.array([1,2,3])
b=np.array([2,3,4])
c=a*b

In [3]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
print (a)
print(a.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)
