In [7]:
import numpy as np
a = np.array([1,3,5])
b = np.array([1,2,3])
print(a*b)

[ 1  6 15]


In [27]:

a=np.array([1,2,3])
b=np.array([2,3,4])
c=a*b

In [9]:
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
print (a)
print(a.shape)
np.sum(a)
np.mean(a)

np.fastCopyAndTranspose(a)

[[1 2 3]
 [3 4 5]]
(2, 3)


C:\Users\Vatsalya Bhadaurya\AppData\Local\Temp\ipykernel_15888\2452661130.py:8: DeprecationWarning: fastCopyAndTranspose and the underlying C function PyArray_CopyAndTranspose have been deprecated.

Use the transpose method followed by a C-order copy instead, e.g. ``arr.T.copy()``
  np.fastCopyAndTranspose(a)


array([[1, 3],
       [2, 4],
       [3, 5]])

In [ ]:
import numpy as np
c=np.random.rand(2,3)
print (c)

[[0.56256501 0.12909235 0.99473707]
 [0.66640028 0.46238479 0.01854922]]


In [ ]:
import numpy as np
d=np.random.randint(1,100, size=(3,3))
print (d)   

[[18 14 31]
 [52 59 29]
 [99  6 17]]


In [73]:
import numpy as np


scores = np.random.randint(50, 101, size=(50, 5))
print(scores)

mean = np.mean(scores)
median_scores = np.median( scores)
deviation = np.std(scores)

print("Mean: ", mean)
print("Median: ", median_scores)
print("Standard Deviation: ", deviation)


[[100  93  84  83  90]
 [ 64  76  67  66  64]
 [ 89  54  65  74  70]
 [ 54  84  85  66  72]
 [ 92  89  56  67  86]
 [ 77  91  70  65  67]
 [ 94  83  73  51  73]
 [ 71  84  53  76  57]
 [ 57  62  99  76  78]
 [ 87  95  87  72  83]
 [ 86  82  56  55  74]
 [ 51  57  80  99  83]
 [ 77  72  55  80  65]
 [ 90  68  68  50  88]
 [ 53  87  87  63  63]
 [ 69  78  76  98  70]
 [ 72  81  50  85  68]
 [ 88  93  74 100  93]
 [ 95  53  80  80  72]
 [ 59  82  89  63  67]
 [ 68  78  55  64  78]
 [ 56  53  82  58  90]
 [ 91  66  92  69  89]
 [ 74  58  93  76  98]
 [ 57  70  78  59  96]
 [ 94  63  68  78  66]
 [ 55  74  93  53  74]
 [ 98  85  61  52  50]
 [ 86  66  98  53  79]
 [ 79  94  73  99  91]
 [ 68  61  92  77  68]
 [ 73  82  79  98  56]
 [ 72  60  76  78  75]
 [100  71  51  82  72]
 [ 88  67  81  69  61]
 [ 54  93  70  51  60]
 [ 94  91 100  83  61]
 [ 95  92  72  76  78]
 [ 63  55  54  96  92]
 [ 65  82  54  77  87]
 [ 71  51  68  79  93]
 [ 64  96  69 100  74]
 [ 71  69  54 100  57]
 [100  70  

In [ ]:
# create a 1d of 10 elel, extarct all elem greater than 5

import numpy as num
arr=[1,2,3,4,5,6,7,8,9,10]
arr1=num.array(arr)
print(arr1[arr1>5])

[ 6  7  8  9 10]


In [7]:
# createw a 1d array consisiting of 12 values(2digit), extarct, all muls of 3

import numpy as num
arr=[12,13,14,15,16,17,18,19,20,21,22,23]
arr1=num.array(arr)
print([arr1%3==0])

[array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False])]


In [29]:
# create 1d array od 3dig elem, repplace all even elem with -1


import numpy as np
arr = np.array([100, 101, 102, 103, 104, 104, 105, 106, 107, 108, 109])
mask = arr % 2 == 0
arr[mask] = -1
print(arr)

[ -1 101  -1 103  -1  -1 105  -1 107  -1 109]


In [35]:
# createa a 1d array of 10 elem, replace all those numbers which are multiple of 3 and 7 both

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10, 21])
mask = (arr % 3 == 0) & (arr % 7 == 0)
arr[mask] = 0
print(arr)

[ 1  2  3  4  5  6  7  8  9 10  0]


In [152]:
# CASE STUDY

# cerate a 2d array consisiting of exam scores of 5 students in 3 subjects, generate a random dataset of 5x3, find the avg scores and subjec wise highest score of each student, normalise the scores using given formula , indentify studens whi scored above 80%

import numpy as np
scores = np.random.randint(40, 98, size=(5, 3))
print(scores)

[[77 84 41]
 [86 45 48]
 [58 84 61]
 [89 71 91]
 [48 46 46]]
